version: '2.1'
services:
  slumos-sand:
    build:
      context: .
      dockerfile: .mvn/Dockerfile
    volumes: ['slumos-sand-data:/home/appuser']
    networks: [backing-services]
    #ports: ['8080:8080']
    #restart: unless-stopped
    #mem_limit: 209715200 # container limit: 200Mb (200 * 1024 * 1024)
volumes:
  slumos-sand-data: {}
networks:
  backing-services:
    driver: bridge
